### PR TITLE
Added ability to cancel movement and drop on same position

### PR DESCRIPTION
**Pull request by SiebeVE**

### CODE REVIEW

**Comment by SiebeVE** [comment]
Ping @colinrcummings, what do you think about this PR?

**Comment by colinrcummings** [comment]
Thanks for your PR @SiebeVE SiebeVE; I'll take a look at this today.

**Comment by SiebeVE** [comment]
@colinrcummings Did you find the time to check this PR?

**Comment by colinrobertbrooks** [comment]
@SiebeVE, what's your use case for this behavior?

**Comment by SiebeVE** [comment]
With this extension I can properly test 2 use cases:
- When the movement is canceled (here simulated by pressing the esc key)
- When the movement isn't cancelled, but dropped in the same position

With the current library you aren't able to do it because it expects a movement and you can't cancel a movement.

**Pull request closed without merging**
