### PR TITLE
Add a getDragElement option to makeDnd

### PR DESCRIPTION
**Pull request by colinrobertbrooks**
See https://github.com/colinrobertbrooks/react-beautiful-dnd-test-utils/pull/12#commitcomment-58933749

**Change Summary**

Added:

- A `getDragElement` option to `makeDnd`. 

**Release**

This will be a minor version.

### CODE REVIEW

**Comment by colinrobertbrooks** [comment]
FYI, @francoisfreitag. 👀

**Review by kayluhb — APPROVED** [review]
LGTM!

**Comment by colinrobertbrooks** [comment]
Released v4.1.0. 🚢

**Comment by francoisfreitag** [comment]
Thanks a ton! Just what I needed, and swiftly released. :rocket:

**Pull request merged**
